FROM openjdk:8-jre-alpine
VOLUME /tmp
#WORKDIR /root/liuhaihua
ADD eureka-server-1.0-SNAPSHOT.jar eureka-server.jar
#ADD eureka-service.sh eureka-service.sh
#ENTRYPOINT ["java","-jar","eureka-server.jar"]
#ENTRYPOINT["nohup","java","-jar","eureka-server.jar",">","eureka-serve8888.log","2>&1","&"]
#ENTRYPOINT ["/bin/sh","/root/liuhaihua/eureka-service.sh"]
